"""game rounds and round submissions

Revision ID: 42fcf93c2c97
Revises: 442380d80809
Create Date: 2026-06-15 22:37:31.924604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42fcf93c2c97'
down_revision: Union[str, None] = '442380d80809'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False, comment='연결된 게임 세션 ID'),
    sa.Column('order_index', sa.Integer(), nullable=False, comment='세션 내 라운드 순서 (1..N)'),
    sa.Column('status', sa.String(length=10), server_default=sa.text("'waiting'"), nullable=False, comment='라운드 상태 (waiting/open/closed)'),
    sa.Column('prompt', sa.Text(), nullable=True, comment='문제/힌트 텍스트'),
    sa.Column('media_url', sa.String(length=255), nullable=True, comment='문제용 미디어 URL (노래 파일 등)'),
    sa.Column('options', sa.JSON(), nullable=True, comment="button 타입 보기 목록 (예: ['1번','2번','3번','4번'])"),
    sa.Column('correct_answer', sa.String(length=255), nullable=True, comment='정답 (공개 전 비노출 — 룰렛 seed 처럼 응답에서 숨김)'),
    sa.Column('opened_at', sa.DateTime(), nullable=True, comment='라운드 오픈 시각'),
    sa.Column('closed_at', sa.DateTime(), nullable=True, comment='라운드 마감 시각'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='라운드 생성한 운영자'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='라운드 상태 변경한 운영자'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='최종 수정 시각'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='생성 시각'),
    sa.CheckConstraint("status IN ('waiting', 'open', 'closed')", name='game_rounds_status_check'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_game_rounds_created_by'),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], name='fk_game_rounds_session'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_game_rounds_updated_by'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'order_index', name='uq_game_rounds_session_order')
    )
    op.create_table('round_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False, comment='연결된 라운드 ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='제출 유저 ID'),
    sa.Column('answer', sa.String(length=255), nullable=False, comment='선택/제출한 답'),
    sa.Column('is_correct', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='정답 여부'),
    sa.Column('server_time', sa.DateTime(), nullable=False, comment='서버 수신 타임스탬프 (클라이언트 시간 무시)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='생성 시각'),
    sa.ForeignKeyConstraint(['round_id'], ['game_rounds.id'], name='fk_round_submissions_round'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_round_submissions_user'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('round_id', 'user_id', name='uq_round_submissions_round_user')
    )
    op.add_column('game_chat_logs', sa.Column('round_id', sa.Integer(), nullable=True, comment='연결된 라운드 ID (라운드제 채팅게임의 문제 단위)'))
    op.create_foreign_key('fk_game_chat_logs_round', 'game_chat_logs', 'game_rounds', ['round_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_game_chat_logs_round', 'game_chat_logs', type_='foreignkey')
    op.drop_column('game_chat_logs', 'round_id')
    op.drop_table('round_submissions')
    op.drop_table('game_rounds')
    # ### end Alembic commands ###
