"""season-scoped teams, soft delete, reward season_id

Revision ID: 442380d80809
Revises: 7f951e30a26c
Create Date: 2026-06-14 22:26:26.197910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '442380d80809'
down_revision: Union[str, None] = '7f951e30a26c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False, comment='소속 시즌 ID'),
    sa.Column('team_id', sa.Integer(), nullable=False, comment='소속 팀 ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='유저 ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='생성 시각'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], name='fk_team_members_season'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name='fk_team_members_team'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_team_members_user'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_id', 'user_id', name='uq_team_members_season_user')
    )
    # rewards 는 이제 시즌별이다. 기존 전역 리워드는 시드로 재생성되므로 정리한다.
    op.execute('DELETE FROM rewards')
    op.add_column('rewards', sa.Column('season_id', sa.Integer(), nullable=False, comment='소속 시즌 ID (시즌별 도감)'))
    op.create_foreign_key('fk_rewards_season', 'rewards', 'seasons', ['season_id'], ['id'])
    op.add_column('seasons', sa.Column('del_yn', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='소프트 삭제 여부'))
    op.add_column('teams', sa.Column('del_yn', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='소프트 삭제 여부'))
    op.drop_constraint('fk_users_team', 'users', type_='foreignkey')
    op.drop_column('users', 'team_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='소속 팀 ID (팀 빌딩 전 NULL)'))
    op.create_foreign_key('fk_users_team', 'users', 'teams', ['team_id'], ['id'])
    op.drop_column('teams', 'del_yn')
    op.drop_column('seasons', 'del_yn')
    op.drop_constraint('fk_rewards_season', 'rewards', type_='foreignkey')
    op.drop_column('rewards', 'season_id')
    op.drop_table('team_members')
    # ### end Alembic commands ###
