"""v2 initial schema

Revision ID: 7f951e30a26c
Revises: 
Create Date: 2026-06-14 00:37:28.061304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f951e30a26c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='시즌 이름 (예: 2026 가평 워크샵, 리허설)'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'preparing'"), nullable=False, comment='시즌 상태 (preparing/active/done)'),
    sa.Column('started_at', sa.DateTime(), nullable=True, comment='시즌 시작 시각'),
    sa.Column('ended_at', sa.DateTime(), nullable=True, comment='시즌 종료 시각'),
    sa.Column('created_by', sa.Integer(), nullable=False, comment='시즌 생성한 운영자'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='최종 수정한 운영자'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='최종 수정 시각'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='생성 시각'),
    sa.CheckConstraint("status IN ('preparing', 'active', 'done')", name='seasons_status_check'),
    sa.PrimaryKeyConstraint('id')
    )
    # 순환 참조 FK (seasons → users): users 가 아직 없으므로 인라인에서 제외 (아래에서 추가)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False, comment='소속 시즌 ID'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='팀 이름'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='생성 시각'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], name='fk_teams_season'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False, comment='로그인 ID'),
    sa.Column('password', sa.String(length=255), nullable=False, comment='비밀번호'),
    sa.Column('nickname', sa.String(length=50), nullable=False, comment='화면 표시 이름'),
    sa.Column('role', sa.String(length=10), nullable=False, comment='권한 (admin/user)'),
    sa.Column('team_id', sa.Integer(), nullable=True, comment='소속 팀 ID (팀 빌딩 전 NULL)'),
    sa.Column('point', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='개인 누적 포인트'),
    sa.Column('profile_image', sa.String(length=255), nullable=True, comment='프로필 이미지 URL'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='최종 수정한 운영자'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='최종 수정 시각'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='생성 시각'),
    sa.CheckConstraint("role IN ('admin', 'user')", name='users_role_check'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name='fk_users_team'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_users_updated'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # 순환 참조 FK: seasons → users (users 생성 이후 추가)
    op.create_foreign_key('fk_seasons_created', 'seasons', 'users', ['created_by'], ['id'])
    op.create_foreign_key('fk_seasons_updated', 'seasons', 'users', ['updated_by'], ['id'])
    op.create_table('buff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='카드 이름 (예: 훈민정음, 왼손잡이)'),
    sa.Column('description', sa.Text(), nullable=False, comment='카드 효과 설명'),
    sa.Column('type', sa.String(length=10), nullable=False, comment='버프/디버프 구분 (buff/debuff)'),
    sa.Column('effect_type', sa.String(length=20), nullable=False, comment='효과 유형'),
    sa.Column('duration', sa.String(length=20), nullable=False, comment='지속 시간 (instant/next_game/two_games/until_used)'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='최종 수정한 운영자'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='최종 수정 시각'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='생성 시각'),
    sa.CheckConstraint("duration IN ('instant', 'next_game', 'two_games', 'until_used')", name='buff_duration_check'),
    sa.CheckConstraint("effect_type IN ('point_penalty', 'point_freeze', 'action_restrict', 'steal', 'reroll', 'double', 'immunity', 'first_pick')", name='buff_effect_type_check'),
    sa.CheckConstraint("type IN ('buff', 'debuff')", name='buff_type_check'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_buff_updated'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False, comment='게임 이름 (예: 노래맞추기, 거짓말 탐지기)'),
    sa.Column('description', sa.Text(), nullable=True, comment='게임 설명 (툴팁 표시용)'),
    sa.Column('participant_type', sa.String(length=20), nullable=False, comment='참여 단위 (team_vs/individual/team_internal/representative)'),
    sa.Column('input_type', sa.String(length=20), nullable=False, comment='참여 방식 (chat/button/offline/puzzle/vote)'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='최종 수정한 운영자'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='최종 수정 시각'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='생성 시각'),
    sa.CheckConstraint("input_type IN ('chat', 'button', 'offline', 'puzzle', 'vote')", name='game_input_type_check'),
    sa.CheckConstraint("participant_type IN ('team_vs', 'individual', 'team_internal', 'representative')", name='game_participant_type_check'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_game_updated'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hidden_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='역할 이름 (예: 사대주의자, 바람잡이)'),
    sa.Column('description', sa.Text(), nullable=False, comment='역할 설명 및 미션 내용'),
    sa.Column('scope', sa.String(length=10), nullable=False, comment='역할 범위 (team/global)'),
    sa.Column('success_condition', sa.Text(), nullable=False, comment='성공 판정 기준'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='최종 수정한 운영자'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='최종 수정 시각'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='생성 시각'),
    sa.CheckConstraint("scope IN ('team', 'global')", name='hidden_roles_scope_check'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_hidden_roles_updated'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rewards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='상품명 (예: 신세계 상품권 5만원)'),
    sa.Column('description', sa.Text(), nullable=True, comment='상품 설명'),
    sa.Column('total_count', sa.Integer(), nullable=False, comment='총 수량'),
    sa.Column('image_url', sa.String(length=255), nullable=True, comment='상품 이미지 URL (도감용)'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='최종 수정한 운영자'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='최종 수정 시각'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='생성 시각'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_rewards_updated'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vote_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='투표 항목 이름 (예: MVP, MUVP, 트롤러)'),
    sa.Column('description', sa.Text(), nullable=True, comment='투표 항목 설명'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='최종 수정한 운영자'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='최종 수정 시각'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='생성 시각'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_vote_items_updated'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timetable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False, comment='소속 시즌 ID'),
    sa.Column('game_id', sa.Integer(), nullable=False, comment='연결된 게임 ID'),
    sa.Column('phase', sa.String(length=50), nullable=True, comment='진행 단계 구분 (예: 저녁식사 전, 저녁식사 후, 2일차)'),
    sa.Column('order_index', sa.Integer(), nullable=False, comment='전체 진행 순서'),
    sa.Column('label', sa.String(length=100), nullable=True, comment='화면 표시용 라벨 (예: 에피타이저, 메인①)'),
    sa.Column('raffle_reward', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='라운드 종료 시 지급할 뽑기권 수'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='최종 수정한 운영자'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='최종 수정 시각'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='생성 시각'),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], name='fk_timetable_game'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], name='fk_timetable_season'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_timetable_updated'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_hidden_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False, comment='소속 시즌 ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='역할 배분된 유저 ID'),
    sa.Column('role_id', sa.Integer(), nullable=False, comment='배분된 역할 ID'),
    sa.Column('is_revealed', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='공개 여부 (시상식 전까지 FALSE)'),
    sa.Column('is_success', sa.Boolean(), nullable=True, comment='미션 성공 여부 (NULL=미판정)'),
    sa.Column('judged_by', sa.Integer(), nullable=True, comment='판정한 운영자'),
    sa.Column('judged_at', sa.DateTime(), nullable=True, comment='판정 시각'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='최종 수정한 운영자'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='최종 수정 시각'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='생성 시각'),
    sa.ForeignKeyConstraint(['judged_by'], ['users.id'], name='fk_user_hidden_roles_judged_by'),
    sa.ForeignKeyConstraint(['role_id'], ['hidden_roles.id'], name='fk_user_hidden_roles_role'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], name='fk_user_hidden_roles_season'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_user_hidden_roles_updated'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_user_hidden_roles_user'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vote_ballots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False, comment='소속 시즌 ID'),
    sa.Column('vote_item_id', sa.Integer(), nullable=False, comment='투표 항목 ID'),
    sa.Column('status', sa.String(length=10), server_default=sa.text("'waiting'"), nullable=False, comment='투표 상태 (waiting/open/closed)'),
    sa.Column('order_index', sa.Integer(), nullable=False, comment='투표 진행 순서'),
    sa.Column('opened_at', sa.DateTime(), nullable=True, comment='투표 시작 시각'),
    sa.Column('closed_at', sa.DateTime(), nullable=True, comment='투표 종료 시각'),
    sa.Column('created_by', sa.Integer(), nullable=False, comment='생성한 운영자'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='최종 수정한 운영자'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='최종 수정 시각'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='생성 시각'),
    sa.CheckConstraint("status IN ('waiting', 'open', 'closed')", name='vote_ballots_status_check'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_vote_ballots_created_by'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], name='fk_vote_ballots_season'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_vote_ballots_updated_by'),
    sa.ForeignKeyConstraint(['vote_item_id'], ['vote_items.id'], name='fk_vote_ballots_vote_item'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timetable_id', sa.Integer(), nullable=False, comment='연결된 타임테이블 항목 ID'),
    sa.Column('state', sa.String(length=20), server_default=sa.text("'idle'"), nullable=False, comment='게임 진행 상태 (idle/ready/in_progress/scoring/reward/done)'),
    sa.Column('seed', sa.String(length=100), nullable=True, comment='룰렛/랜덤 결과 생성용 서버 시드값'),
    sa.Column('started_at', sa.DateTime(), nullable=True, comment='게임 시작 시각'),
    sa.Column('ended_at', sa.DateTime(), nullable=True, comment='게임 종료 시각'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='상태 변경한 운영자'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='최종 수정 시각'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='생성 시각'),
    sa.CheckConstraint("state IN ('idle', 'ready', 'in_progress', 'scoring', 'reward', 'done')", name='game_sessions_state_check'),
    sa.ForeignKeyConstraint(['timetable_id'], ['timetable.id'], name='fk_game_sessions_timetable'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_game_sessions_updated'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vote_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ballot_id', sa.Integer(), nullable=False, comment='연결된 투표지 ID'),
    sa.Column('voter_id', sa.Integer(), nullable=False, comment='투표한 유저 ID'),
    sa.Column('target_id', sa.Integer(), nullable=False, comment='투표 대상 유저 ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='생성 시각'),
    sa.ForeignKeyConstraint(['ballot_id'], ['vote_ballots.id'], name='fk_vote_records_ballot'),
    sa.ForeignKeyConstraint(['target_id'], ['users.id'], name='fk_vote_records_target'),
    sa.ForeignKeyConstraint(['voter_id'], ['users.id'], name='fk_vote_records_voter'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ballot_id', 'voter_id', name='uq_vote_records_ballot_voter')
    )
    op.create_table('envelopes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False, comment='발행된 게임 세션 ID'),
    sa.Column('number', sa.Integer(), nullable=False, comment='봉투 번호'),
    sa.Column('content_type', sa.String(length=10), nullable=False, comment='봉투 내용물 유형 (reward/blank)'),
    sa.Column('reward_id', sa.Integer(), nullable=True, comment='내용물이 상품일 때 rewards.id'),
    sa.Column('buff_id', sa.Integer(), nullable=True, comment='꽝 봉투에 동봉된 버프/디버프 카드 ID'),
    sa.Column('owner_type', sa.String(length=10), nullable=True, comment='봉투 소유 단위 (team/user)'),
    sa.Column('owner_id', sa.Integer(), nullable=True, comment='owner_type에 따라 teams.id 또는 users.id'),
    sa.Column('is_opened', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='개봉 여부'),
    sa.Column('opened_at', sa.DateTime(), nullable=True, comment='개봉 시각'),
    sa.Column('created_by', sa.Integer(), nullable=False, comment='봉투 생성한 운영자'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='최종 수정한 운영자'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='최종 수정 시각'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='생성 시각'),
    sa.CheckConstraint("content_type IN ('reward', 'blank')", name='envelopes_content_type_check'),
    sa.CheckConstraint("owner_type IN ('team', 'user')", name='envelopes_owner_type_check'),
    sa.ForeignKeyConstraint(['buff_id'], ['buff.id'], name='fk_envelopes_buff'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_envelopes_created_by'),
    sa.ForeignKeyConstraint(['reward_id'], ['rewards.id'], name='fk_envelopes_reward'),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], name='fk_envelopes_session'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_envelopes_updated_by'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_chat_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False, comment='연결된 게임 세션 ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='채팅 입력 유저'),
    sa.Column('message', sa.String(length=255), nullable=False, comment='입력 메시지'),
    sa.Column('is_correct', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='정답 여부'),
    sa.Column('server_time', sa.DateTime(), nullable=False, comment='서버 수신 타임스탬프 (클라이언트 시간 무시)'),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], name='fk_game_chat_logs_session'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_game_chat_logs_user'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False, comment='연결된 게임 세션 ID'),
    sa.Column('subject_type', sa.String(length=10), nullable=False, comment='결과 단위 (team/user)'),
    sa.Column('subject_id', sa.Integer(), nullable=False, comment='최종 승자 팀/유저 ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='생성 시각'),
    sa.CheckConstraint("subject_type IN ('team', 'user')", name='game_results_subject_type_check'),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], name='fk_game_results_session'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_score_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False, comment='연결된 게임 세션 ID'),
    sa.Column('subject_type', sa.String(length=10), nullable=False, comment='점수 단위 (team/user)'),
    sa.Column('subject_id', sa.Integer(), nullable=False, comment='subject_type에 따라 teams.id 또는 users.id'),
    sa.Column('score', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='획득 점수'),
    sa.Column('memo', sa.String(length=255), nullable=True, comment='부가정보 (예: 수영 01:23, 자전거 02:45)'),
    sa.Column('created_by', sa.Integer(), nullable=False, comment='점수 기입한 운영자'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='점수 수정한 운영자'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='최종 수정 시각'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='생성 시각'),
    sa.CheckConstraint("subject_type IN ('team', 'user')", name='game_score_logs_subject_type_check'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_game_score_logs_created_by'),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], name='fk_game_score_logs_session'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_game_score_logs_updated_by'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raffle_tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True, comment='관련 게임 세션 ID (운영자 직접 부여 시 NULL)'),
    sa.Column('owner_type', sa.String(length=10), nullable=False, comment='뽑기권 소유 단위 (team/user)'),
    sa.Column('owner_id', sa.Integer(), nullable=False, comment='owner_type에 따라 teams.id 또는 users.id'),
    sa.Column('action', sa.String(length=10), nullable=False, comment='획득/사용/몰수 (earned/used/lost)'),
    sa.Column('amount', sa.Integer(), nullable=False, comment='변동 수량'),
    sa.Column('reason', sa.String(length=255), nullable=True, comment='사유 (예: 게임보상, 도박승리, 운영자부여, 봉투뽑기)'),
    sa.Column('created_by', sa.Integer(), nullable=False, comment='기록한 운영자 또는 시스템'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='생성 시각'),
    sa.CheckConstraint("action IN ('earned', 'used', 'lost')", name='raffle_tickets_action_check'),
    sa.CheckConstraint("owner_type IN ('team', 'user')", name='raffle_tickets_owner_type_check'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_raffle_tickets_created_by'),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], name='fk_raffle_tickets_session'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_buffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False, comment='대상 팀 ID'),
    sa.Column('buff_id', sa.Integer(), nullable=False, comment='보유한 버프/디버프 ID'),
    sa.Column('session_id', sa.Integer(), nullable=False, comment='부여된 게임 세션 ID'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='현재 활성 여부'),
    sa.Column('activated_at', sa.DateTime(), nullable=True, comment='실제 발동 시각'),
    sa.Column('expires_after', sa.Integer(), nullable=True, comment='만료되는 게임 세션 ID'),
    sa.Column('created_by', sa.Integer(), nullable=False, comment='부여한 운영자'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='최종 수정한 운영자'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='최종 수정 시각'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='생성 시각'),
    sa.ForeignKeyConstraint(['buff_id'], ['buff.id'], name='fk_team_buffs_buff'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_team_buffs_created_by'),
    sa.ForeignKeyConstraint(['expires_after'], ['game_sessions.id'], name='fk_team_buffs_expires'),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], name='fk_team_buffs_session'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name='fk_team_buffs_team'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_team_buffs_updated_by'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 순환 참조 FK 먼저 제거 (users drop 전에)
    op.drop_constraint('fk_seasons_updated', 'seasons', type_='foreignkey')
    op.drop_constraint('fk_seasons_created', 'seasons', type_='foreignkey')
    op.drop_table('team_buffs')
    op.drop_table('raffle_tickets')
    op.drop_table('game_score_logs')
    op.drop_table('game_results')
    op.drop_table('game_chat_logs')
    op.drop_table('envelopes')
    op.drop_table('vote_records')
    op.drop_table('game_sessions')
    op.drop_table('vote_ballots')
    op.drop_table('user_hidden_roles')
    op.drop_table('timetable')
    op.drop_table('vote_items')
    op.drop_table('rewards')
    op.drop_table('hidden_roles')
    op.drop_table('game')
    op.drop_table('buff')
    op.drop_table('users')
    op.drop_table('teams')
    op.drop_table('seasons')
    # ### end Alembic commands ###
